title: I'm Juhee KIM
description: Web Engineer
site_title: 'Portfolio_JuheeKIM'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: juhee0614
blog_url: https://www.nagekar.com
email: wwwss7@naver.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 